

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.define "mysqldb" do |mysql|
    mysql.vm.network "public_network"
    mysql.vm.synced_folder "./configs", "/configs"
  end

  config.vm.define "phpweb" do |web|
    web.vm.network "forwarded_port", guest:8888, host:8089
    web.vm.network "public_network"

    web.vm.provision "shell", inline:
    "sudo apt-get install -y puppet"

    web.vm.provision "puppet" do |pup|
      pup.manifests_path ="./configs/manifests"
      pup.manifest_file="phpweb.pp"
    end

    web.vm.synced_folder "./configs", "/configs"
  end

end

