

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory=512
    vb.cpus=1
  end

  config.vm.define "mysqldb" do |mysql|
    mysql.vm.network "public_network"
    mysql.vm.synced_folder "./configs", "/configs"
  end

  config.vm.define "phpweb" do |web|
    web.vm.network "forwarded_port", guest:8888, host:8089
    web.vm.network "public_network"

    web.vm.provision "shell", inline:
    "sudo apt-get install -y puppet"

    web.vm.provision "puppet" do |pup|
      pup.manifests_path ="./configs/manifests"
      pup.manifest_file="phpweb.pp"
    end

    web.vm.synced_folder "./configs", "/configs"
  end

  config.vm.define "mysqlserver" do |mysqlserver|
    mysqlserver.vm.network "public_network", ip:"192.168.100.200"
    mysqlserver.vm.provision "shell", inline: "cat /vagrant/configs/keys/ansible.pub >> .ssh/authorized_keys"
    mysqlserver.vm.synced_folder "./", "/vagrant"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network"
    ansible.vm.synced_folder "./configs", "/configs"
    ansible.vm.synced_folder "./", "/vagrant"

    ansible.vm.provision "shell", inline: 
    "cp /configs/keys/ansible /home/vagrant && \
     chmod 600 /home/vagrant/ansible"

    ansible.vm.provision "shell", inline:
    "apt-get update && \
    apt-get install -y software-properties-common && \
    apt-add-repository --yes --update ppa:ansible/ansible && \
    apt-get install -y ansible && \
    sudo chown vagrant:vagrant /home/vagrant/ansible "

    ansible.vm.provision "shell", inline:
    "ansible-playbook -i /configs/ansible/hosts /configs/ansible/playbook.yml"
  end

end

